# Use Python base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements if you have them
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy your Python script
COPY data_ingestion/ .

# Command to run your script
CMD ["python", "run_all.py"]
