apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: qoe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: qoe/dashboard-backend:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: qoe
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
